spring:
  application:
    name: open-resume-platform
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
logging:
  level:
    com:
      reynolds: DEBUG
server:
  port: 9000
pandoc-client-config:
    url: http://localhost:8080/convert