spring:
  application:
    name: open-resume-platform
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
logging:
  level:
    com:
      reynolds: DEBUG
pandoc:
  client:
    url: https://webhook.site/5263ee87-8ad8-4480-b608-967e9ebccb63